using MargamParkArchives.Core.DataAccess.ArtefactEntity;
using MargamParkArchives.Core.DataAccess.CategoryEntity;
using MargamParkArchives.Core.DataAccess.CreatorEntity;
using MargamParkArchives.Core.DataAccess.GeneralLocationEntity;
using MargamParkArchives.Core.DataAccess.IdentifierGroupEntity;
using MargamParkArchives.Core.DataAccess.PeriodEntity;
using MargamParkArchives.Core.DataAccess.SpecificLocationEntity;
using MargamParkArchives.Core.Database;
using MargamParkArchives.Core.Entities.ArtefactEntity;
using MargamParkArchives.Core.Entities.ValidationHelpers;
using MargamParkArchives.Data.Connections;
using System.Text;

namespace MargamParkArchives.Data.Entities.ArtefactEntity;

public class MySqlArtefactWriter(IMySqlDataAccess dataAccess, IIdentifierGroupReader identifierGroupReader,
    ICategoryReader categoryReader, IPeriodReader periodReader, ICreatorReader creatorReader,
    IGeneralLocationReader generalLocationReader, ISpecificLocationReader specificLocationReader) : IArtefactWriter
{
    /// <summary>
    /// Note identifier number and identifier key are generated by triggers.
    /// </summary>
    private const string InsertArtefactQuery = "insert into {0} (identifier_group_id, file_path, parent_id, notes, " +
        "title_en, title_cy, description_en, description_cy, category_id, tags_cy, culture_tag_en, period_id, " +
        "creator_id, location_coverage, right_type_1, right_holder_1_en, right_holder_1_cy, visual_artefact, " +
        "general_location_id, specific_location_id) " +
        "values (@IdentifierGroupId, @FilePath, @ParentId, @Notes, @TitleEn, @TitleCy, @DescriptionEn, @DescriptionCy, " +
        "@CategoryId, @TagsCy, @CultureTagEn, @PeriodId, @CreatorId, @LocationCoverage, @RightType1, @RightHolder1En, " +
        "@RightHolder1Cy, @VisualArtefact, @GeneralLocationId, @SpecificLocationId);";
    private const string GetLastIdentifierKeyQuery = "select identifier_key from {0} where identifier_group_id = @IdentifierGroupId order by identifier_number desc limit 1;";

    private const string IdentifierGroupNotFoundErrorMessage = "Identifier group {0} does not exist.";
    private const string CategoryNotFoundErrorMessage = "Category {0} does not exist.";
    private const string PeriodNotFoundErrorMessage = "Period {0} does not exist.";
    private const string CreatorNotFoundErrorMessage = "Creator {0} does not exist.";
    private const string GeneralLocationNotFoundErrorMessage = "General location {0} does not exist.";
    private const string SpecificLocationNotFoundErrorMessage = "Specific location {0} does not exist.";
    private const string IdentifierKeyRetrievalFailedMessage = "Failed to retrieve identifier key after artefact creation.";
    private const string ArtefactCreationFailedMessage = "Failed to create artefact.";

    private readonly IMySqlDataAccess _dataAccess = dataAccess;
    private readonly IIdentifierGroupReader _identifierGroupReader = identifierGroupReader;
    private readonly ICategoryReader _categoryReader = categoryReader;
    private readonly IPeriodReader _periodReader = periodReader;
    private readonly ICreatorReader _creatorReader = creatorReader;
    private readonly IGeneralLocationReader _generalLocationReader = generalLocationReader;
    private readonly ISpecificLocationReader _specificLocationReader = specificLocationReader;

    #region Public IArtefactWriter Methods

    public async Task<string> CreateArtefactAsync(ArtefactCreateDto artefact)
    {
        // Validate artefact
        StringBuilder errorList = new();
        await ValidateLinkedEntitiesExist(artefact, errorList);
        ValidateAllRightsInformation(artefact, errorList);
        ValidateArtefactContent(artefact, errorList);
        ValidateArtefactClassification(artefact, errorList);
        string errors = errorList.ToString();
        if (!string.IsNullOrEmpty(errors))
        {
            throw new ValidationException(errors);
        }

        string sqlQuery = string.Format(InsertArtefactQuery, DatabaseConstants.ArtefactTableName);
        bool success = await _dataAccess.InsertAsync<ArtefactCreateDto>(sqlQuery, artefact);
        if (success)
        {
            string? lastIdentifierKey = await GetLastIdentifierKeyForGroupImplementationAsync() ??
                throw new DatabaseException(IdentifierKeyRetrievalFailedMessage);
            return lastIdentifierKey;
        }
        else
        {
            throw new DatabaseException(ArtefactCreationFailedMessage);
        }
    }

    public Task<bool> UpdateArtefactAsync(ArtefactUpdateDto artefact)
    {
        throw new NotImplementedException();
    }

    public async Task<string?> GetLastIdentifierKeyForGroupAsync(string identifierGroupId)
    {
        bool isValidIdentifierGroupId = await _identifierGroupReader.IdentifierGroupExists(identifierGroupId);
        if (!isValidIdentifierGroupId)
        {
            string errorMessage = string.Format(IdentifierGroupNotFoundErrorMessage, identifierGroupId);
            throw new ValidationException(errorMessage, nameof(identifierGroupId));
        }

        return await GetLastIdentifierKeyForGroupImplementationAsync();
    }

    #endregion Public IArtefactWriter Methods

    #region Private Helper Methods

    private async Task<string?> GetLastIdentifierKeyForGroupImplementationAsync()
    {
        string sqlQuery = string.Format(GetLastIdentifierKeyQuery, DatabaseConstants.ArtefactTableName);
        string? lastIdentifierKey = await _dataAccess.GetSingleValueAsync<string, object>(sqlQuery, new { IdentifierGroupId = identifierGroupId });
        return lastIdentifierKey;
    }

    private async Task ValidateLinkedEntitiesExist(ArtefactCreateDto artefact, StringBuilder errorList)
    {
        bool isValidIdentifierGroupId = await _identifierGroupReader.IdentifierGroupExists(artefact.IdentifierGroupId);
        if (!isValidIdentifierGroupId)
        {
            string errorMessage = string.Format(IdentifierGroupNotFoundErrorMessage, artefact.IdentifierGroupId);
            errorList.AppendLine(errorMessage);
        }

        bool isValidCategoryId = artefact.CategoryId == null || await _categoryReader.CategoryExists(artefact.CategoryId);
        if (!isValidCategoryId)
        {
            string errorMessage = string.Format(CategoryNotFoundErrorMessage, artefact.CategoryId);
            errorList.AppendLine(errorMessage);
        }

        bool isValidPeriodId = artefact.PeriodId == null || await _periodReader.PeriodExists((int)artefact.PeriodId);
        if (!isValidPeriodId)
        {
            string errorMessage = string.Format(PeriodNotFoundErrorMessage, artefact.PeriodId);
            errorList.AppendLine(errorMessage);
        }

        bool isValidCreatorId = artefact.CreatorId == null || await _creatorReader.CreatorExists((int)artefact.CreatorId);
        if (!isValidCreatorId)
        {
            string errorMessage = string.Format(CreatorNotFoundErrorMessage, artefact.CreatorId);
            errorList.AppendLine(errorMessage);
        }

        bool isGeneralLocationIdValid = artefact.GeneralLocationId == null ||
            await _generalLocationReader.GeneralLocationExists((int)artefact.GeneralLocationId);
        if (!isGeneralLocationIdValid)
        {
            string errorMessage = string.Format(GeneralLocationNotFoundErrorMessage, artefact.GeneralLocationId);
            errorList.AppendLine(errorMessage);
        }

        bool isSpecificLocationIdValid = artefact.SpecificLocationId == null ||
            await _specificLocationReader.SpecificLocationExists((int)artefact.SpecificLocationId);
        if (!isSpecificLocationIdValid)
        {
            string errorMessage = string.Format(SpecificLocationNotFoundErrorMessage, artefact.SpecificLocationId);
            errorList.AppendLine(errorMessage);
        }
    }

    private void ValidateAllRightsInformation(ArtefactCreateDto artefact, StringBuilder errorList)
    {
        ValidateRightsInformation(artefact.RightType1, nameof(artefact.RightType1), errorList);
        ValidateRightsInformation(artefact.RightHolder1En, nameof(artefact.RightHolder1En), errorList);
        ValidateRightsInformation(artefact.RightHolder1Cy, nameof(artefact.RightHolder1Cy), errorList);
    }

    private static void ValidateRightsInformation(string? rightsInformation, string propertyName, StringBuilder errorList)
    {
        bool isValidRightType1 = ArtefactRightsInformationValidationRules.IsValidRightsInformation(
            rightsInformation, propertyName, out string errorMessage);
        if (!isValidRightType1)
        {
            errorList.AppendLine(errorMessage);
        }
    }

    private static void ValidateArtefactClassification(ArtefactCreateDto artefact, StringBuilder errorList)
    {
        bool isValidParentId = ArtefactClassificationValidationRules.IsValidParentId(
                    artefact.ParentId, nameof(artefact.ParentId), out string parentIdError);
        if (!isValidParentId)
        {
            errorList.AppendLine(parentIdError);
        }
        bool isValidTagsCy = ArtefactClassificationValidationRules.IsValidClassificaionText(
            artefact.TagsCy, nameof(artefact.TagsCy), out string tagsCyError);
        if (!isValidTagsCy)
        {
            errorList.AppendLine(tagsCyError);
        }
        bool isValidCultureTagEn = ArtefactClassificationValidationRules.IsValidClassificaionText(
            artefact.TagsCy, nameof(artefact.TagsCy), out string cultureTagEn);
        if (!isValidCultureTagEn)
        {
            errorList.AppendLine(cultureTagEn);
        }
        bool isValidLocationCoverage = ArtefactClassificationValidationRules.IsValidClassificaionText(
            artefact.LocationCoverage, nameof(artefact.LocationCoverage), out string locationCoverageError);
        if (!isValidLocationCoverage)
        {
            errorList.AppendLine(locationCoverageError);
        }
    }

    private static void ValidateArtefactContent(ArtefactCreateDto artefact, StringBuilder errorList)
    {
        bool isValidTitleEn = ArtefactContentValidationRules.IsValidTitle(
                    artefact.TitleEn, nameof(artefact.TitleEn), out string titleEnError);
        if (!isValidTitleEn)
        {
            errorList.AppendLine(titleEnError);
        }
        bool isValidTitleCy = ArtefactContentValidationRules.IsValidTitle(
            artefact.TitleCy, nameof(artefact.TitleCy), out string titleCyError);
        if (!isValidTitleCy)
        {
            errorList.AppendLine(titleCyError);
        }
        bool isValidDescriptionEn = ArtefactContentValidationRules.IsValidDescription(
            artefact.DescriptionEn, nameof(artefact.DescriptionEn), out string descriptionEnError);
        if (!isValidDescriptionEn)
        {
            errorList.AppendLine(descriptionEnError);
        }
        bool isValidDescriptionCy = ArtefactContentValidationRules.IsValidDescription(
            artefact.DescriptionCy, nameof(artefact.DescriptionCy), out string descriptionCyError);
        if (!isValidDescriptionCy)
        {
            errorList.AppendLine(descriptionCyError);
        }
    }

    #endregion Private Helper Methods
}
